name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: rakudo-star:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Raku version
      run: raku -v

    - name: Add the buster backports for monit
      run:  echo "deb http://ftp.de.debian.org/debian buster-backports main" >/etc/apt/sources.list.d/buster-backports.list

    - name: apt update
      run:  apt-get -qq update

    - name: install monit
      run: apt-get -qq install -y monit

    - name: fix the monit config
      run:  sed -i -e '$ a \set httpd port 2812 and use address 0.0.0.0 allow admin:monit' /etc/monit/monitrc

    - name: start monit
      run:  service monit start

    - name: Install dependencies
      run: zef install --deps-only --/test --test-depends .

    - name: Run tests
      run: zef test -v --debug .
      env:
        MONIT_TEST_LIVE: 1
        MONIT_TEST_CONTROL: 1
